#!/bin/bash

echo "🧪 =============================================="
echo "🧪 STOP MUSIC DETAILED TEST"
echo "🧪 =============================================="
echo ""
echo "This script will help diagnose why stop music isn't working."
echo ""
echo "SETUP:"
echo "1. Backend is already running (PID 41524)"
echo "2. We'll rebuild Flutter with enhanced logging"
echo "3. You'll test stop music"
echo "4. We'll analyze the logs"
echo ""

read -p "Press ENTER to rebuild Flutter app with enhanced logging..."

echo ""
echo "📱 Rebuilding Flutter app..."
cd frontend_flutter
flutter build macos --debug

if [ $? -ne 0 ]; then
    echo "❌ Flutter build failed!"
    exit 1
fi

echo ""
echo "✅ Flutter rebuilt successfully!"
echo ""
echo "================================================"
echo "📋 TEST PROCEDURE:"
echo "================================================"
echo ""
echo "1. Open Spotify Desktop app (if not already open)"
echo "2. Run: open -a Spotify"
echo ""
echo "3. Start the Flutter app in a NEW terminal:"
echo "   cd /Users/robenhai/Never\ Alone/frontend_flutter"
echo "   flutter run -d macos"
echo ""
echo "4. In the app, start a conversation and say:"
echo "   \"תנגן לי מוזיקה\" (play me music)"
echo ""
echo "5. Wait for music to play (Spotify will open)"
echo ""
echo "6. Then say:"
echo "   \"עצור את המוזיקה\" (stop the music)"
echo ""
echo "7. Watch BOTH terminals (backend + Flutter)!"
echo ""
echo "================================================"
echo "🔍 WHAT TO LOOK FOR IN FLUTTER CONSOLE:"
echo "================================================"
echo ""
echo "When you say \"עצור את המוזיקה\", you should see:"
echo ""
echo "✅ SUCCESS PATH (if event arrives):"
echo "   🌐 RAW WebSocket Event: \"stop-music\""
echo "   🎵🎵🎵 STOP-MUSIC EVENT DETECTED IN onAny!"
echo "   🎵🎵🎵 WebSocketService: ===== STOP MUSIC EVENT RECEIVED ====="
echo "   🎵 RealtimeConversationManager: Stop music requested"
echo "   🎵🎵🎵 ConversationScreen: ===== STOP MUSIC CALLBACK TRIGGERED ====="
echo "   🎵🎵🎵 ConversationScreen: ===== EXECUTING STOP SPOTIFY PLAYBACK ====="
echo ""
echo "❌ FAILURE PATH (if event doesn't arrive):"
echo "   (You'll see NONE of the above logs)"
echo "   (Backend will show broadcast, but Flutter shows nothing)"
echo ""
echo "================================================"
echo "📊 AFTER TEST:"
echo "================================================"
echo ""
echo "Copy the COMPLETE output from Flutter terminal and share it."
echo "We need to see if the event arrives at all."
echo ""
echo "Key questions to answer:"
echo "1. Did onAny catch the 'stop-music' event? (🌐 RAW WebSocket Event)"
echo "2. Did the specific listener fire? (===== STOP MUSIC EVENT RECEIVED =====)"
echo "3. Did the callback reach the screen? (===== STOP MUSIC CALLBACK TRIGGERED =====)"
echo ""
echo "Good luck! 🍀"
echo ""
